# Generated by Django 4.2.5 on 2023-09-22 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_studenthistory_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='lastdate',
            field=models.DateField(default=datetime.date(2023, 9, 22)),
        ),
    ]
